name: run-tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [8.1, 8.2, 8.3]
        laravel: [ 9.*, 10.* ]
        stability: [ prefer-stable ]
        include:
          - laravel: 10.*
            testbench: 8.*
          - laravel: 9.*
            testbench: 7.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: secretroot
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, zip, pcntl, pdo_mysql

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/pest
        env:
          DB_USERNAME: laravel
          DB_PASSWORD: secret
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

