name: "Run Tests for laravel 8 & 9"
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: secret
          MYSQL_DATABASE: sql_logger
          MYSQL_ROOT_PASSWORD: topsecret
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      APP_ENV: testing
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_DATABASE: sql_logger
      DB_USERNAME: user
      DB_PASSWORD: secret
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.0, 8.1 ]
        laravel: [ 8.*, 9.* ]
        stability:
          #- prefer-lowest
          - prefer-stable
        include:
          - laravel: 9.*
            testbench: 7.*
          - laravel: 8.*
            testbench: ^6.23

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, zip, pcntl, pdo_mysql
      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction
      - name: Execute tests
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: vendor/bin/pest
